server:
  port: 8082

spring:
  dataSource:
    url: jdbc:mysql://localhost:3306/FPVBB?allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver